
name: publish documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Regular checkout
      uses: actions/checkout@v4
      with:
        ref: doc

    - name: Merge and push
      run: |
        echo "Auto-merge ${{ github.ref_name }} to doc branch"
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch --tags origin
        git merge ${{ github.ref_name }} -m "Auto-merge ${{ github.ref_name }} to doc branch"
        git push